#!/bin/bash
set -e
echo "deploy testnet AFFECTING testnet USERS?"
read -p "Press any key to continue..."
cargo build 
anchor build -v
cp target/idl/marinade_program.json res/
cp keys/marinade_finance-keypair.json target/deploy/
solana program deploy -v -u testnet --program-id keys/marinade_finance-keypair.json target/deploy/marinade_finance.so  --upgrade-authority keys/marinade_finance-keypair.json